---

- name: Update all packages
  yum:
    name: "*"
    state: latest
  register: update_all_packages
  become: yes

- block:
    - name: Reboot host
      shell: sleep 5 && shutdown -r now
      async: 300
      poll: 0
      become: yes

    - name: Wait for nodes to boot
      wait_for:
        host: ""
        port: 22
        delay: 30
        timeout: 600
        search_regex: OpenSSH
      delegate_to: localhost
  when: "'kernel' in update_all_packages.results"

- name: Install required packages
  yum:
    name:
      - atomic-openshift-utils
    state: present
  become: yes

- name: Install preferred packages
  yum:
    name:
      - vim
      - screen
    state: present
  become: yes

- name: Copy EC2 key
  copy:
    src: "{{ ec2_key_file }}"
    dest: ~/.ssh/id_rsa
    mode: 0600
    backup: yes
