---

- hosts: localhost
  roles:
    - provision_aws
    - host_facts_aws

- hosts: openshift_nodes:&openshift_cluster_{{ cluster_name }}
  vars:
    provision_type: aws
  any_errors_fatal: yes
  roles:
    - rhsm_subscribe
    - host_prep_openshift

- hosts: openshift_role_bastion:&openshift_cluster_{{ cluster_name }}
  vars:
    provision_type: aws
  any_errors_fatal: yes
  roles:
    - rhsm_subscribe
    - host_prep_bastion
    - install_openshift

- hosts: openshift_role_master:&openshift_cluster_{{ cluster_name }}
  roles:
    - create_users
