---

- hosts: localhost
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
  roles:
    - provision_aws
    - host_facts_aws

- hosts: openshift_nodes:&openshift_cluster_{{ cluster_name }}
  vars:
    provision_type: aws
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
  any_errors_fatal: yes
  roles:
    - rhsm_subscribe
    - host_prep_openshift

- hosts: openshift_role_bastion:&openshift_cluster_{{ cluster_name }}
  vars:
    provision_type: aws
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
  any_errors_fatal: yes
  roles:
    - rhsm_subscribe
    - host_prep_bastion
    - install_openshift
