---

- hosts: localhost
  gather_facts: no
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
  tasks:
    - name: Start EC2 instances
      ec2_instance:
        region: "{{ aws_region }}"
        filters:
          tag:OpenShiftClusterName: "{{ cluster_name }}"
        state: started
