---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Stop EC2 instances
      ec2_instance:
        region: "{{ aws_region }}"
        filters:
          tag:OpenShiftClusterName: "{{ cluster_name }}"
        state: stopped
