---

- name: Istio install - Backup master config
  copy:
    src: /etc/origin/master/master-config.yaml
    dest: /etc/origin/master/master-config.yaml.prepatch
  become: yes

- name: Istio install - Patch master config
  command: oc ex config patch master-config.yaml.prepatch -p "$(cat master-config.patch)" > master-config.yaml
  args:
    chdir: /etc/origin/master/
  become: yes

- name: Istio install - Restart master API server and controllers
  command: /usr/local/bin/master-restart api && /usr/local/bin/master-restart controllers
  become: yes

- name: Istio install - Install operator
  command: oc new-project istio-operator && oc new-project istio-system && oc apply -n istio-operator -f https://raw.githubusercontent.com/Maistra/istio-operator/maistra-0.10/deploy/servicemesh-operator.yaml
  become: yes

- name: Istio install - Copy control plane config
  copy:
    src: istio-installation.yaml
    dest: ~/istio-installation.yaml
  become: yes

- name: Istio install - Install the control plane
  command: oc create -n istio-system -f ~/istio-installation.yaml
  become: yes
